# Generated by Django 2.2.1 on 2019-11-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitHubRunner', '0002_auto_20191124_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
