# Generated by Django 2.2.1 on 2019-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('institution', models.CharField(max_length=30)),
                ('yearStarted', models.IntegerField(max_length=4)),
                ('yearEnded', models.IntegerField(max_length=4)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('companyName', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('description', models.TextField(max_length=4000)),
            ],
        ),
    ]
