# Generated by Django 2.2.1 on 2019-12-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='yearEnded',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='yearStarted',
            field=models.IntegerField(),
        ),
    ]
