# Generated by Django 2.2.1 on 2020-02-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191207_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(null=True, upload_to='./db/images'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='companyName',
            field=models.TextField(max_length=30),
        ),
    ]
