# Generated by Django 2.2.1 on 2020-02-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200214_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(null=True, upload_to='./db/images'),
        ),
    ]
