# Generated by Django 2.2.1 on 2020-02-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200214_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(null=True, upload_to='./home/db/images'),
        ),
    ]
