# Generated by Django 2.2.1 on 2020-02-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200214_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='companyName',
            field=models.TextField(max_length=40),
        ),
    ]
