# Generated by Django 2.2.1 on 2020-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200214_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='logo',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
